[versions]
# libraries
junit5 = "5.14.1"
junit4 = "4.13.2"
opentest4j = "1.3.0"
mockk = "1.14.5"

# plugins
changelog = "2.4.0"          # https://github.com/JetBrains/gradle-changelog-plugin/releases
intelliJPlatform = "2.10.4"  # https://github.com/JetBrains/intellij-platform-gradle-plugin/releases
kotlin = "2.2.0"             # https://kotlinlang.org/docs/releases.html
kover = "0.9.3"
qodana = "2025.2.1"
versions = "0.53.0"

[libraries]
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit5" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
junit-vintage = { group = "org.junit.vintage", name = "junit-vintage-engine" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
